<a href="https://colab.research.google.com/github/Sarbartha07/Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

a = ((1,2,3),(0,1,4))

aa = np.array (a)

print (aa)

[[1 2 3]
 [0 1 4]]


In [ ]:
import numpy as np
from numpy import random

x = random.randint (100)

print(x)

90


In [ ]:
# Genarating array with 5 random number

x = random.randint (100, size=(5))

print(x)

[18 24 83 84 14]


In [ ]:
# Generating 2 diamentional arrey with 5 random number

x = random.randint (100, size = (3, 5))

print(x)

[[ 4 22 68  5 86]
 [48 72 64 73 72]
 [82 30 70 76 82]]


In [ ]:
# Generating 3 diamentional arrey with 5 random number

x = random.randint (100, size = (3, 5, 5))

print(x)

[[[57 64 23 77 85]
  [ 2 77 85 26 77]
  [83 70 96  4 87]
  [25  5 37 97 71]
  [83 78 68 21 47]]

 [[23 34 91 67 36]
  [66 90 94 58 15]
  [47 78 16 24 38]
  [48 32 96 34 83]
  [96 54 54 67 51]]

 [[58 20 54 31 27]
  [59 18 12 52 45]
  [50 40 69  9 20]
  [90 36 59 18 38]
  [44 15 88 36 36]]]


In [ ]:
x = np.arange(0, 11)

print (x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
c = np.ones((2,3), dtype=np.int16)

print (c)

[[1 1 1]
 [1 1 1]]


In [3]:
a = np.array([[1,2,3], [0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c

print (a)
print (b)
print (c)
print (d)

[[1 2 3]
 [0 1 4]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[2 3 4]
 [1 2 5]]


In [4]:
import numpy as np

orig_array_1 = np.array ([10,32,36,34,4, 55])
print (orig_array_1.shape)

(6,)


In [5]:
reshaped_arr_1 = orig_array_1.reshape(3,2)

print(reshaped_arr_1)

[[10 32]
 [36 34]
 [ 4 55]]


In [15]:
import numpy as np

original_array = np.array ([[10,12,34], [40,4,100]])

reshaped_array = original_array.reshape (6,)

print(original_array)
print(reshaped_array)

[[ 10  12  34]
 [ 40   4 100]]
[ 10  12  34  40   4 100]


In [17]:
x = np.arange(12, dtype=float)
x = x.reshape(4, 3)
np.ones_like(x)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
x = np.array([[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0],[1.0,1.0,1.0]])
x = x.reshape(4, 3)
np.ones_like(x)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
x = np.arange(12)
x = x.reshape(4, 3)
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
import numpy as np
x = np.array ([[1,2,3],[5,6,9]])
print (x)
reshaped = x.reshape(3,-1)

print(reshaped)

[[1 2 3]
 [5 6 9]]
[[1 2]
 [3 5]
 [6 9]]


In [1]:
import numpy as np

array_example = np.array ([[10,32,36,34],
                           [125,851,0,-24],
                           [56,19,75,20],
                           [3,-7,4,2.0]])

print(array_example[:, 1])

[ 32. 851.  19.  -7.]


In [4]:
condition =  array_example > 40

print (condition)

[[False False False False]
 [ True  True False False]
 [ True False  True False]
 [False False False False]]


In [6]:
print (array_example[condition])

[125. 851.  56.  75.]


In [14]:
import numpy as np

a = [[2,4,6,8,10,12,14],
     [3,6,9,12,15,18,21],
     [4,8,12,16,20,24,28],
     [5,10,15,20,25,30,35],
     [6,12,18,24,30,36,42],
     [7,14,21,28,35,42,49]]

b = np.array(a)

print (b[0:6,0:7])

[[ 2  4  6  8 10 12 14]
 [ 3  6  9 12 15 18 21]
 [ 4  8 12 16 20 24 28]
 [ 5 10 15 20 25 30 35]
 [ 6 12 18 24 30 36 42]
 [ 7 14 21 28 35 42 49]]


In [23]:
import numpy as np

x = [[ 3, 6, 9, 12],

     [15, 18, 21, 24],

     [27, 30, 33, 36],

     [39, 42, 45, 48],

     [51, 54, 57, 60]]

y = np.array (x)

print (y[::2,1::2])

[[ 6 12]
 [30 36]
 [54 60]]


In [1]:
import numpy as np

Ages = np.array([10, 32, 42, 35, 31, 25, 58, 26, 33, 34, 39, 50, 40, 38, 30, 27, 60, 29])

print (Ages)

below_25 = Ages <= 25
print (len(Ages[below_25]), Ages[below_25])

between_25to40 = (Ages >= 25) & (Ages <= 40)
print (len(Ages[between_25to40]),Ages[between_25to40])

[10 32 42 35 31 25 58 26 33 34 39 50 40 38 30 27 60 29]
2 [10 25]
13 [32 35 31 25 26 33 34 39 40 38 30 27 29]


In [1]:
import numpy as np

array_multiID = np.array([[100, 14, 76, 54],
                         [125, 81, 0, -24],
                         [566, 159, 175, 20],
                         [38, -47, 84, 22.0]], dtype = int)

print(array_multiID[1])

array_multiID [1] = 5
print(array_multiID[1])
print(array_multiID)

[125  81   0 -24]
[5 5 5 5]
[[100  14  76  54]
 [  5   5   5   5]
 [566 159 175  20]
 [ 38 -47  84  22]]


In [2]:
import numpy as np

## 'student_name',  'subject_a',  'subject_b',  'subject_c',  'subject_d',  'subject_e'
#     1                 2             3             4             5             6

student_array = np.array ([['student_1', 59, 64, 94, 87,81],
                           ['student_2', 8, 56, 18, 58, 69],
                           ['student_3', 7, 20, 60, 63, 64],
                           ['student_4', 71, 94, 71, 68, 13],
                           ['student_5', 89, 1, 16, 33, 40],
                           ['student_6', 4, 25, 48, 41, 84],
                           ['student_7', 3, 79, 46, 9, 71],
                           ['student_8', 87, 77, 75, 15, 69],
                           ['student_9', 61, 1, 48, 98, 23],
                           ['student_10', 98, 60, 24, 66, 56],
                           ['student_11', 58, 12, 75, 7, 98],
                           ['student_12', 23, 62, 6, 35, 37],
                           ['student_13', 14, 25, 87, 56, 8],
                           ['student_14', 68, 1, 81, 11, 61],
                           ['student_15', 11, 69, 35, 17, 66]], dtype = object)

print(student_array)

[['student_1' 59 64 94 87 81]
 ['student_2' 8 56 18 58 69]
 ['student_3' 7 20 60 63 64]
 ['student_4' 71 94 71 68 13]
 ['student_5' 89 1 16 33 40]
 ['student_6' 4 25 48 41 84]
 ['student_7' 3 79 46 9 71]
 ['student_8' 87 77 75 15 69]
 ['student_9' 61 1 48 98 23]
 ['student_10' 98 60 24 66 56]
 ['student_11' 58 12 75 7 98]
 ['student_12' 23 62 6 35 37]
 ['student_13' 14 25 87 56 8]
 ['student_14' 68 1 81 11 61]
 ['student_15' 11 69 35 17 66]]


In [9]:
# Number of students who have scored higher in subject_a than subject_b

print("subject_a score of allstudents :", student_array[:, 1])
print("subject_b score of allstudents :", student_array[:, 2])

Higher_Score_in_A = student_array[:,1] > student_array[:,2]

print(student_array[Higher_Score_in_A][:,0:3])
print(len(student_array[Higher_Score_in_A]))

subject_a score of allstudents : [59 8 7 71 89 4 3 87 61 98 58 23 14 68 11]
subject_b score of allstudents : [64 56 20 94 1 25 79 77 1 60 12 62 25 1 69]
[['student_5' 89 1]
 ['student_8' 87 77]
 ['student_9' 61 1]
 ['student_10' 98 60]
 ['student_11' 58 12]
 ['student_14' 68 1]]
6


In [13]:
## Average score of subject_a and subject_b
print("Average score of Subject A: ",student_array[:, 1].mean())
print("Average score of Subject B: ",student_array[:, 2].mean())

Average score of Subject A:  44.06666666666667
Average score of Subject B:  43.06666666666667


In [15]:
sum(student_array[:, 1] > student_array[:, 2])

6

In [20]:
# Average score in subject_a

Sub_A = student_array[:, 1]
Sub_A
Total_Score = sum(student_array[:,1])
Total_Score
Student_Count = len(student_array)
Student_Count
Average_Score_A = Total_Score/Student_Count
Average_Score_A

44.06666666666667

In [3]:
# Number of students who have scored higher than student_15 in both subject A & B

Student_15_A = student_array[14, 1]
Student_15_B = student_array[14, 2]

print(Student_15_A)
print(Student_15_B)

Rest_Student_A = student_array [0:14, 1]
Rest_Student_B = student_array [0:14, 2]

print(Rest_Student_A)
print(Rest_Student_B)

Student_Count = (Rest_Student_A > Student_15_A) & (Rest_Student_B > Student_15_B)

Result = sum(Student_Count)

print ("Number of students who have scored higher than student_15 in both subject A & B:", Result)

print(student_array[0:14][Student_Count][:, 0:3])


11
69
[59 8 7 71 89 4 3 87 61 98 58 23 14 68]
[64 56 20 94 1 25 79 77 1 60 12 62 25 1]
Number of students who have scored higher than student_15 in both subject A & B: 2
[['student_4' 71 94]
 ['student_8' 87 77]]


In [19]:
## What is the average of total marks scored by student 4 to 10

Student_4_10 = student_array [3:10, 1:6]

Total_Marks = Student_4_10.sum(axis = 1)

Average_Marks = Total_Marks.mean()

print(Total_Marks, Average_Marks, sep =" - ")


[317 179 202 208 323 231 304] - 252.0


In [17]:
from numpy.core.multiarray import where
## Count the number of who scored more than 20 in subject A

Score_A = student_array [:, 1]

Student_with_morethan_20  = Score_A > 20

Count = where(Student_with_morethan_20)

print(Count)
print(sum(Student_with_morethan_20))


(array([ 0,  3,  4,  7,  8,  9, 10, 11, 13]),)
9


In [21]:
## If any student get less than 20 in sub_a then make it 35 for passing.

sub_a = student_array [:, 1]

new_score = where(sub_a < 20, 35, sub_a)

new_score

array([59, 35, 35, 71, 89, 35, 35, 87, 61, 98, 58, 23, 35, 68, 35],
      dtype=object)

In [32]:
a = np.unique(student_array[:, 1:], return_index = True)

a

(array([1, 3, 4, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 20, 23, 24,
        25, 33, 35, 37, 40, 41, 46, 48, 56, 58, 59, 60, 61, 62, 63, 64, 66,
        68, 69, 71, 75, 77, 79, 81, 84, 87, 89, 94, 98], dtype=object),
 array([21, 30, 25, 57, 10,  5, 33, 68, 51, 19, 60, 38, 22, 73,  7, 11, 44,
        47, 26, 23, 58, 59, 24, 28, 32, 27,  6,  8,  0, 12, 40, 56, 13,  1,
        48, 18,  9, 15, 37, 36, 31,  4, 29,  3, 20,  2, 43]))

In [35]:
np.arange(3) + 5

array([5, 6, 7])

In [2]:
import numpy as np

banking_array = np.array([[30.0, 'unemployed', 'married', 1787.0, 'no', 'no', 'cellular','oct'],

       [33.0, 'services', 'married', 4789.0, 'yes', 'yes', 'cellular','may'],

       [35.0, 'management', 'single', 1350.0, 'yes', 'no', 'cellular','apr'],

       [30.0, 'management', 'married', 1476.0, 'yes', 'yes', 'unknown','jun'],

       [59.0, 'blue-collar', 'married', 0.0, 'yes', 'no', 'unknown','may'],

       [35.0, 'management', 'single', 747.0, 'no', 'no', 'cellular','feb'],

       [36.0, 'self-employed', 'married', 307.0, 'yes', 'no', 'cellular','may'],

       [39.0, 'technician', 'married', 147.0, 'yes', 'no', 'cellular','may'],

       [41.0, 'entrepreneur', 'married', 221.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'services', 'married', -88.0, 'yes', 'yes', 'cellular','apr'],

       [39.0, 'services', 'married', 9374.0, 'yes', 'no', 'unknown','may'],

       [43.0, 'admin.', 'married', 264.0, 'yes', 'no', 'cellular', 'apr'],

       [36.0, 'technician', 'married', 1109.0, 'no', 'no', 'cellular','aug'],

       [20.0, 'student', 'single', 502.0, 'no', 'no', 'cellular', 'apr'],

       [31.0, 'blue-collar', 'married', 360.0, 'yes', 'yes', 'cellular','jan'],

       [40.0, 'management', 'married', 194.0, 'no', 'yes', 'cellular','aug'],

       [56.0, 'technician', 'married', 4073.0, 'no', 'no', 'cellular','aug'],

       [37.0, 'admin.', 'single', 2317.0, 'yes', 'no', 'cellular', 'apr'],

       [25.0, 'blue-collar', 'single', -221.0, 'yes', 'no', 'unknown','may'],

       [31.0, 'services', 'married', 132.0, 'no', 'no', 'cellular','jul']], dtype=object)

print(banking_array)

[[30.0 'unemployed' 'married' 1787.0 'no' 'no' 'cellular' 'oct']
 [33.0 'services' 'married' 4789.0 'yes' 'yes' 'cellular' 'may']
 [35.0 'management' 'single' 1350.0 'yes' 'no' 'cellular' 'apr']
 [30.0 'management' 'married' 1476.0 'yes' 'yes' 'unknown' 'jun']
 [59.0 'blue-collar' 'married' 0.0 'yes' 'no' 'unknown' 'may']
 [35.0 'management' 'single' 747.0 'no' 'no' 'cellular' 'feb']
 [36.0 'self-employed' 'married' 307.0 'yes' 'no' 'cellular' 'may']
 [39.0 'technician' 'married' 147.0 'yes' 'no' 'cellular' 'may']
 [41.0 'entrepreneur' 'married' 221.0 'yes' 'no' 'unknown' 'may']
 [43.0 'services' 'married' -88.0 'yes' 'yes' 'cellular' 'apr']
 [39.0 'services' 'married' 9374.0 'yes' 'no' 'unknown' 'may']
 [43.0 'admin.' 'married' 264.0 'yes' 'no' 'cellular' 'apr']
 [36.0 'technician' 'married' 1109.0 'no' 'no' 'cellular' 'aug']
 [20.0 'student' 'single' 502.0 'no' 'no' 'cellular' 'apr']
 [31.0 'blue-collar' 'married' 360.0 'yes' 'yes' 'cellular' 'jan']
 [40.0 'management' 'married' 194.

In [48]:
## What is the total bank balance of the first 5 records from the data?
first_5 = banking_array[0:5, 3]

Bank_balance = sum (first_5)
print(Bank_balance)

## What is the average bank balance?

All_bal= banking_array [:, 3]

Average = All_bal.mean()
print(Average)


9402.0
1442.0


In [4]:
## Count the number of people who has a housing?

Housing = banking_array [:, 4]

Count = sum(Housing == 'yes')
Count

13

In [9]:
## Count the number of people who has a loan?

Loan = banking_array[:, 5]

Count_Loan = np.where(Loan == 'yes', 1, 0)
Total = sum(Count_Loan)

Total

5

In [3]:
## No of people who have a "cellular" contact and also "married" and hold a "management" job?

Job = banking_array [:, 1]
Married = banking_array [:, 2]
Contact = banking_array[:, 6]

Cond = np.where ((Job == 'management') & (Married == 'married') & (Contact == 'cellular'), 1, 0)

Total = sum(Cond)
Total

1

In [9]:
## Find the total balance of the customers aged between 25 and 40(both inclusive).

Age = banking_array [:, 0]
Balance = banking_array[:, 3]

Cond = np.where((Age >= 25) & (Age <= 40), Balance, 0)
Total_Balance = sum(Cond)

Total_Balance

23868.0

In [14]:
## No of people who are single but have more than average bank balance?

Status = banking_array [:, 2]
Average_Balance = np.mean(banking_array[:,3])

Cond = np.where ((Status == 'single') & (banking_array[:,3]> Average_Balance), 1, 0)
Count = sum(Cond)
Count

1

In [42]:
## No of people who had a loan and housing?

Count = np.where ((banking_array [:, 4] == 'yes') & (banking_array [:, 5] == 'yes'), 1, 0)

Count.sum()

4

## Company has decided to give a bonus of 5% of their account balance to those account holders whose age is more than or equal to 55 years and whose account balance is more than 2000. Calculate the sum of the total bank balance to the account holders(mentioned above) after crediting their bonus amount.

In [48]:
from typing import Final
Age = banking_array [:,0]
Age
Balance = banking_array[:,3]

Cond = np.where ((Age >= 55) & (Balance > 2000), Balance, 0)
Final_Bal = Cond*1.05
Final_Bal.sum()

4276.650000000001

In [51]:
a = np.array([17, 11, 19]) # 1x3 Dimension array
b = 3
c = a + b
c

array([20, 14, 22])