Write a lambda function to find all strings from a given list whose length is greater than 5.
strings = ['hello', 'world', 'python', 'programming', 'is', 'fun']
threshold = 5

In [2]:
strings = ['hello', 'world', 'python', 'programming', 'is', 'fun']
threshold = 5

length =  lambda x : len(x) > threshold

result = filter(length,strings)
print(list(result))

['python', 'programming']


Create a function that takes a list of dictionaries, where each dictionary represents a student with "name" and "marks" keys, and returns a new list of dictionaries with an additional key "status". The "status" should be "pass" if the "marks" is greater than or equal to 60, otherwise "fail". Use function, lambda function and map to accomplish this task.

students = [ {"name": "John", "marks": 80}, {"name": "Jane", "marks": 45}, {"name": "Bob", "marks": 70}, {"name": "Alice", "marks": 35}, ]

In [3]:
students = [ {"name": "John", "marks": 80}, {"name": "Jane", "marks": 45}, {"name": "Bob", "marks": 70}, {"name": "Alice", "marks": 35}, ]
def status(students):
  add_status = lambda x : {**x, "status" : "pass" if x["marks"] >= 60 else "fail"}
  updated_students = list(map(add_status,students))
  return updated_students

print(status(students))

[{'name': 'John', 'marks': 80, 'status': 'pass'}, {'name': 'Jane', 'marks': 45, 'status': 'fail'}, {'name': 'Bob', 'marks': 70, 'status': 'pass'}, {'name': 'Alice', 'marks': 35, 'status': 'fail'}]


Given a list of dictionaries containing information about students (name, age, grade), use lambda and reduce functions to find the average grade of all students.
students = [ {"name": "John", "age": 20, "grade": 85}, {"name": "Jane", "age": 21, "grade": 90}, {"name": "Bob", "age": 19, "grade": 75}, {"name": "Alice", "age": 22, "grade": 95} ]

In [4]:
from functools import reduce

students = [ {"name": "John", "age": 20, "grade": 85},
            {"name": "Jane", "age": 21, "grade": 90}, {"name": "Bob", "age": 19, "grade": 75},
             {"name": "Alice", "age": 22, "grade": 95} ]

def avg_score(students):
  sum = lambda y, x : y + x["grade"]
  total_grade = reduce(sum,students,0)
  new_avg = total_grade/ len(students)
  return new_avg

print(avg_score(students))


86.25


Create a program that takes a list of dictionaries, where each dictionary contains the name and age of a person. Use lambda functions to filter out all the dictionaries for which the age is less than 30. Then, use a lambda function to print the names of the persons in the sorted list, with the name capitalized and prefixed with "Mr." or "Ms." depending on their gender.

In [5]:
people= [
    {"name": "John", "age": 25, "gender": "male"},
    {"name": "Emily", "age": 35, "gender": "female"},
    {"name": "Alex", "age": 28, "gender": "male"},
    {"name": "Sarah", "age": 30, "gender": "female"},
    {"name": "Max", "age": 42, "gender": "male"},
]

def age_30(people):
  age_below = lambda x : x["age"] <= 30
  updated_people = list(filter(age_below, people))
  return updated_people


a = age_30(people)

def new_people(a):
  name_new = lambda y: {**y, "name" : ("Ms" if y["gender"] == "female" else "Mr") +" "+y["name"].upper() }
  updated_new_people = list(map(name_new,a))
  return updated_new_people

print(new_people(a))

[{'name': 'Mr JOHN', 'age': 25, 'gender': 'male'}, {'name': 'Mr ALEX', 'age': 28, 'gender': 'male'}, {'name': 'Ms SARAH', 'age': 30, 'gender': 'female'}]


In [6]:
people= [
    {"name": "John", "age": 25, "gender": "male"},
    {"name": "Emily", "age": 35, "gender": "female"},
    {"name": "Alex", "age": 28, "gender": "male"},
    {"name": "Sarah", "age": 30, "gender": "female"},
    {"name": "Max", "age": 42, "gender": "male"},
]

def age_30(people):
  age_below = lambda x : x["age"] <= 30
  updated_people = list(filter(age_below, people))
  return updated_people

a = age_30(people)
print(a)

def new_people(a):
  name_new = lambda y: {("Ms." if y["gender"] == "female" else "Mr.") +" "+ y["name"].upper()}
  updated_new_people = list(map(name_new,a))
  return updated_new_people

print(new_people(a))

[{'name': 'John', 'age': 25, 'gender': 'male'}, {'name': 'Alex', 'age': 28, 'gender': 'male'}, {'name': 'Sarah', 'age': 30, 'gender': 'female'}]
[{'Mr. JOHN'}, {'Mr. ALEX'}, {'Ms. SARAH'}]


In [7]:
import pandas as pd
import numpy as np

x = np.array([21,22,23,24,25])
y = pd.Series(x)
y.index = ['A','B','C','D','E']
print(y)

A    21
B    22
C    23
D    24
E    25
dtype: int64


Create a set having 5 elements (weight in KG) and convert it into a pandas dataframe, add label as index (use these names: "Shailesh", "Sai", "Harsha", "Jagdeesh", "Mujeeb") also and give column name as Weight.

In [8]:
a = [68,72,82,55,95]
weights = pd.DataFrame(a, columns = ['Weight'])
weights.index = ['Shailesh', 'Sai', 'Harsha', 'Jagdeesh', 'Mujeeb']
print(weights)

          Weight
Shailesh      68
Sai           72
Harsha        82
Jagdeesh      55
Mujeeb        95


Convert a dictionary with two keys, "name" and "Percentage", and their corresponding values, into a tabular format using pandas dataframe function. Add index also in the dataframe as index = index.
name = ["Sam", "Arvind", "Sai"]
Percentage = [90, 95, 85]
index = [1, 2, 3]

In [9]:
name = ["Sam", "Arvind", "Sai"]
Percentage = [90, 95, 85]
index = [1, 2, 3]

a = {'name': name, 'Percentage': Percentage}
b = pd.DataFrame(a, index = index)
b

name  Percentage
1     Sam          90
2  Arvind          95
3     Sai          85

Merge multiple given dataframes without calling merge function multiple times. You also need all observations from all dataframes.

In [10]:

import pandas as pd
player = ['Player1','Player2','Player3', 'Player4']
score = [88,92,63, 22]
df1 = pd.DataFrame({'Player':player, 'Scores': score})
print(df1)


player = ['Player1','Player2','Player4']
wicket = [0,1,5]
df2 = pd.DataFrame({'Player':player, 'Wickets': wicket})
print(df2)


player = ['Player4','Player2','Player3']
catches = [0, 2, 1]
df3 = pd.DataFrame({'Player':player, 'Catch': catches})
print(df3)


player = ['Player4','Player5','Player3']
fifty = [0, 2, 1]
df4 = pd.DataFrame({'Player':player, 'Fifty': fifty})
print(df4)

## Merging all dataframes

merged_df = df1.merge(df2, on='Player', how='outer') \
               .merge(df3, on='Player', how='outer') \
               .merge(df4, on='Player', how='outer')

print(merged_df)

    Player  Scores
0  Player1      88
1  Player2      92
2  Player3      63
3  Player4      22
    Player  Wickets
0  Player1        0
1  Player2        1
2  Player4        5
    Player  Catch
0  Player4      0
1  Player2      2
2  Player3      1
    Player  Fifty
0  Player4      0
1  Player5      2
2  Player3      1
    Player  Scores  Wickets  Catch  Fifty
0  Player1    88.0      0.0    NaN    NaN
1  Player2    92.0      1.0    2.0    NaN
2  Player3    63.0      NaN    1.0    1.0
3  Player4    22.0      5.0    0.0    0.0
4  Player5     NaN      NaN    NaN    2.0


Please check if anything else than A, G, C, T is present in a DNA sequence using search function.
ATGCGCCTACAATCGGTACGTCATCGCGC@@@@@TTACGGCTCGGCTCTCNNNCGGGCCTGCGCGCGCCTGATCGA

In [11]:
import re

string = "ATGCGCCTACAATCGGTACGTCATCGCGC@@@@@TTACGGCTCGGCTCTCNNNCGGGCCTGCGCGCGCCTGATCGA"


# Regular expression to match sequences that do not contain "AGCT"
pattern = re.compile(r'[^AGCT]+')

# Find all matches using re.finditer
matches = pattern.finditer(string)

# Iterate through the matches and print the spans
for match in matches:
    print(f"Span: {match.start()} - {match.end()}")


Span: 29 - 34
Span: 50 - 53


Here are height and weight of five persons. Please create a dataframe and then create BMI column. BMI = weight/(height^2).
heights = [1.65, 1.75, 1.80, 1.62, 1.68]
weights = [65, 70, 80, 55, 62]

In [12]:
heights = [1.65, 1.75, 1.80, 1.62, 1.68]
weights = [65, 70, 80, 55, 62]

heights_s = pd.Series(heights)
weights_s = pd.Series(weights)

BMI = weights_s/(heights_s**2)

x = {'heights' : heights_s, 'weights' : weights_s, 'BMI': BMI}
y = pd.DataFrame(x)
y


heights  weights        BMI
0     1.65       65  23.875115
1     1.75       70  22.857143
2     1.80       80  24.691358
3     1.62       55  20.957171
4     1.68       62  21.967120

Split the text from numbers.

Information = "There are 60 students in DS15 batch."

In [13]:
import re
info = "There are 60 students in DS15 batch."

a = re.split('\d', info)

a



['There are ', '', ' students in DS', '', ' batch.']

Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

Expected output:

 [[0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]

 [0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]]

In [14]:
import numpy as np

a = np.zeros(shape = (8,8), dtype = int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Create a 2d array of 8*8 matrix with 1 on the border and 0 inside

Expected output:

 [[1 1 1 1 1 1 1 1]

 [1 0 0 0 0 0 0 1]

 [1 0 0 0 0 0 0 1]

 [1 0 0 0 0 0 0 1]

 [1 0 0 0 0 0 0 1]

 [1 0 0 0 0 0 0 1]

 [1 0 0 0 0 0 0 1]

 [1 1 1 1 1 1 1 1]]

In [15]:
import numpy as np

x = np.zeros(shape = (8,8), dtype = int)

x[:,0] = 1
x[0,:] = 1
x[-1,:] = 1
x[:,-1] = 1
x

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

Create a 3x3 matrix with values ranging from 0 to 8

Expected output:

 [[0 1 2]

 [3 4 5]

 [6 7 8]]

In [16]:
x =[]
for i in range (0,9):
  x.append(i)

import numpy as np

a = np.array(x)
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a vector with values ranging from 10 to 49 and then reverse the vector.

In [17]:
a = []
for i in range (10,50):
  a.append(i)

b = np.array(a)
b[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

What are the smallest and largest values of the column “reason for absence”.

In [18]:
x = 'reason for absence'
a = len(x)

18

Find all words in a string that start with a vowel.

string = 'Apples are red, bananas are yellow, and oranges are orange.'

In [42]:
import re

string = 'Apples are red, bananas are yellow, and oranges are orange.'

# Define vowels as a set for efficient lookup
vowels = {'a', 'e', 'i', 'o', 'u', 'A', 'E', 'I', 'O', 'U'}

# Split the string into words
words = re.findall(r'\b\w+\b', string)
print(words)
# Iterate over each word and check if it starts with a vowel
for word in words:
    if word[0] in vowels:
        # Strip punctuation marks from the word
        word = re.sub(r'[^\w\s]', '', word)
        print(word)

['Apples', 'are', 'red', 'bananas', 'are', 'yellow', 'and', 'oranges', 'are', 'orange']
Apples
are
are
and
oranges
are
orange


In [44]:
import re

string = 'Please contact us at support@example.com for assistance or info@example.com for more information.'

# Define the pattern for an email address
pattern = r'[\w\.-]+@[\w\.-]+'

# Use re.findall() to extract all email addresses matching the pattern
emails = re.findall(pattern, string)

# Print the extracted email addresses
for email in emails:
    print(email)


support@example.com
info@example.com


Validate a US phone number using regular expressions. The phone number should be in the format "XXX-XXX-XXXX" (where X is a digit).

phone_number = '123-456-7890'

In [45]:
import re

phone_number = '123-456-7890'


pattern = r'^\d{3}-\d{3}-\d{4}$'


match = re.match(pattern, phone_number)

if match:
    print(f"Valid phone number")

Valid phone number
